project_id: '527056'
files:
  - source: /config/locales/en.yml
    translation: /config/locales/%locale%.yml
  - source: /config/locales/devise/devise.en.yml
    translation: /config/locales/devise/devise.%locale%.yml
  - source: /config/locales/backend/backend.en.yml
    translation: /config/locales/backend/backend.%locale%.yml
