"project_id": "527056"
"preserve_hierarchy": true

"files": [
  {
    "source": "/config/locales/en.yml",
    "ignore": [
      "/config/locales/activerecord",
      "/config/locales/devise"
    ],
    "translation": "/config/locales/%two_letters_code%.yml"
  },
  {
    "source": "/config/locales/devise/devise.en.yml",
    "translation": "/config/locales/devise/devise.%two_letters_code%.yml"
  },
  {
    "source": "/config/locales/activerecord/activerecord.en.yml",
    "translation": "/config/locales/activerecord/activerecord.%two_letters_code%.yml"
  }
]