apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dbinitready-configmap-access
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dbinitready-configmap-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dbinitready-configmap-access
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}