apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.image.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.image.name }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.web.port }}